#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add($container->get('App\Console\Shell'));
$app->add($container->get('App\Console\Server'));
$app->run();
